// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Smart-Flask

#include "../ui.h"


void ui_event_comp_Brightness_Brightness(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t ** comp_Brightness = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_checked_set_text_value(comp_Brightness[UI_COMP_BRIGHTNESS_BRIGHTNESS], target, "100", "");
    }
}

// COMPONENT Brightness

lv_obj_t * ui_Brightness_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Brightness;
    cui_Brightness = lv_label_create(comp_parent);
    lv_obj_set_width(cui_Brightness, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Brightness, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Brightness, -8);
    lv_obj_set_y(cui_Brightness, 54);
    lv_obj_set_align(cui_Brightness, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(cui_Brightness, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Brightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BRIGHTNESS_NUM);
    children[UI_COMP_BRIGHTNESS_BRIGHTNESS] = cui_Brightness;
    lv_obj_add_event_cb(cui_Brightness, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Brightness, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_Brightness, ui_event_comp_Brightness_Brightness, LV_EVENT_ALL, children);
    ui_comp_Brightness_create_hook(cui_Brightness);
    return cui_Brightness;
}

