// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Smart-Flask

#ifndef _SMART_FLASK_UI_COMP_HOOK_H
#define _SMART_FLASK_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_Brightness_create_hook(lv_obj_t * comp);
void ui_comp_Button1_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
