// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Smart-Flask

#ifndef _UI_COMP_BRIGHTNESS_H
#define _UI_COMP_BRIGHTNESS_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Brightness
#define UI_COMP_BRIGHTNESS_BRIGHTNESS 0
#define _UI_COMP_BRIGHTNESS_NUM 1
lv_obj_t * ui_Brightness_create(lv_obj_t * comp_parent);
void ui_event_comp_Brightness_Brightness(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
